name: MTRec
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  
  - pandas
  - scikit-learn
  - umap-learn
  - wget
  - pip
  - pip:
    - plotly==5.20.0
    - numpy==1.20.1
    - pyvi==0.1.1
    - PyYAML==5.4.1
    - PyYAML==6.0.1
    - torch==2.0.1
    - torchmetrics==1.1.2
    - tqdm==4.59.0
    - transformers==4.33.1
    - jupyter
    - requests

